spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: devproject0001@outlook.com
    password: aQbNoQQ5&9$gSc8c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bolton_ecommerce?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
jwt:
  secret: zSLkGjZCe1mJbkLlI77Mw9eP0wx7XZJC5TbIE6/F5we7brZ0Pp+Et9e0A4QXNWaA
